# IMAGEN BASE
FROM node
# DIRECTORIO DE TRABAJO DENTRO DEL CONTENEDOR
WORKDIR /clase4/docker
# COPIAMOS EL PACKAGE.JSON
COPY package.json ./
# INSTALAMOS LAS DEPENDENCIAS
RUN npm install
# COPIAMOS EL RESTO DE LOS ARCHIVOS
COPY . .
# EXPONEMOS EL PUERTO DE NUESTRA APP
EXPOSE 3000
# COMANDOS PARA EJECUTAR LA APP
CMD ["node", "clase4/docker/app.js"]
