// LOGUEARSE DESDE LA CONSOLA A NPM
// npm login

// EL NAME PUESTO EN PACKAGE.JSON SERA EL NOMBRE CON EL QUE SE PUBLICA

// PARA PUBLICAR EL PAQUETE HACER:
// npm publish --access public

// PARA INSTALARLO EN OTRO PROYECTO HACER:
// npm install muestraoperacionescoder2

// ACA YA HEMOS IMPORTADO ELDESARROLLADO EN CLASE
// EN LA CARPETA NODE_,MODULES SE ENCUENTRA EL PAQUETE Y PUEDEN VER SU CONTENIDO

// RECUERDEN QUE LA PROPIEDAD "MAIN" DEL PACKAGE.JSON INDICA EL ARCHIVO DE ENTRADA 
// DEL PAQUETE, ASI QUE LAS FUNCIONALIDADES QUE DESARROLLAMOS DEBEN ESTAR 
// EXPORTADAS DESDE ESE ARCHIVO

import operaciones from 'muestraoperacionescoder2';

operaciones.division(4,2);